export const notificationFilters = [
  { key: "All", count: 12 },
  { key: "Investment", count: 2 },
  { key: "Community", count: 3 },
  { key: "Mentions", count: 2 },
  { key: "Projects", count: 2 },
  { key: "Newsletter", count: 1 },
  { key: "Events", count: 1 },
  { key: "Payments", count: 1 },
] as const;

export const notifications = [
  {
    category: "Investment" as const,
    icon: "mdi:bullseye-arrow",
    tone: "bg-bull/15 text-bull",
    title: "Investment Update",
    isNew: true,
    text: "Your inquiry INV-2024-0002 has been reviewed. Your advisor, Sarah Johnson, has prepared a recommendation for you.",
    time: "10 minutes ago",
    unread: true,
  },
  {
    category: "Community" as const,
    icon: "mdi:forum-outline",
    tone: "bg-primary/15 text-primary",
    title: "New reply in Forex Community",
    isNew: false,
    text: 'TraderPro replied to your post "EUR/USD technical analysis for next week".',
    time: "1 hour ago",
    unread: true,
  },
  {
    category: "Mentions" as const,
    icon: "mdi:at",
    tone: "bg-gold/15 text-gold",
    title: "You were mentioned",
    isNew: false,
    text: '@DavidO in Crypto Community by CryptoMaster: "Great insights on BTC breakout!"',
    time: "2 hours ago",
    unread: true,
  },
  {
    category: "Projects" as const,
    icon: "mdi:briefcase-outline",
    tone: "bg-violet-400/15 text-violet-400",
    title: "Project Update",
    isNew: true,
    text: 'Your project "AI Trading Bot Development" has moved to the Development stage.',
    time: "3 hours ago",
    unread: true,
    progress: { label: "Development", value: 60 },
  },
  {
    category: "Newsletter" as const,
    icon: "mdi:email-outline",
    tone: "bg-sky-400/15 text-sky-400",
    title: "Newsletter",
    isNew: false,
    text: "Your weekly market insights newsletter is here.",
    time: "5 hours ago",
    unread: false,
  },
  {
    category: "Events" as const,
    icon: "mdi:calendar-month",
    tone: "bg-amber-400/15 text-amber-400",
    title: "Upcoming Event Reminder",
    isNew: false,
    text: '"AI in Trading: Building Smarter Strategies" starts in 2 days.',
    time: "Yesterday, 6:00 PM",
    unread: false,
  },
  {
    category: "Payments" as const,
    icon: "mdi:cash-multiple",
    tone: "bg-bull/15 text-bull",
    title: "Payment Successful",
    isNew: false,
    text: "Your payment of $49.00 for News Terminal Pro (Monthly) was successful.",
    time: "Yesterday, 4:15 PM",
    unread: false,
  },
  {
    category: "Community" as const,
    icon: "mdi:forum-outline",
    tone: "bg-primary/15 text-primary",
    title: "New reply in Stocks Community",
    isNew: false,
    text: 'InvestorJoe replied to your comment on "Apple Q2 Earnings Discussion".',
    time: "May 23, 2024, 9:30 AM",
    unread: false,
  },
];

export const filterCategories = [
  { label: "Unread", count: 6 },
  { label: "Investment Updates", count: 2 },
  { label: "Community Replies", count: 3 },
  { label: "Mentions", count: 2 },
  { label: "Project Updates", count: 2 },
  { label: "Newsletter", count: 1 },
  { label: "Events", count: 1 },
  { label: "Payments", count: 1 },
];

export const notificationSummary = {
  new: 6,
  read: 2,
  total: 8,
  breakdown: [
    { label: "Investment", pct: 16.7, tone: "bg-bull" },
    { label: "Community", pct: 25.0, tone: "bg-primary" },
    { label: "Mentions", pct: 16.7, tone: "bg-gold" },
    { label: "Projects", pct: 16.7, tone: "bg-violet-400" },
    { label: "Newsletter", pct: 8.3, tone: "bg-sky-400" },
    { label: "Events", pct: 8.3, tone: "bg-amber-400" },
    { label: "Payments", pct: 8.3, tone: "bg-rose-400" },
  ],
};
